ItemApp/urls.py
from django.urls import path
from .views import GetProjectsList, GetProjectDetail, GetUserProjectsList, CreateProject, LikeView, FlagView, UpdateProject, DeleteProject
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name='showcase')),
    path("Showcase/", GetProjectsList.as_view(), name="showcase"),
    path('Showcase/<int:pk>/', GetProjectDetail.as_view(), name="project"),
    path('Showcase/User/', GetUserProjectsList.as_view(), name="user_projects"),
    path('Showcase/User/<int:pk>/', GetProjectDetail.as_view(), name="project"),
    path('Showcase/User/create-project/', CreateProject.as_view(), name='create_project'),
    path('Showcase/User/update-project/<int:pk>/', UpdateProject.as_view(), name='update_project'),
    path('Showcase/User/delete-project/<int:pk>/', DeleteProject.as_view(), name='delete_project'),
    path('Showcase/User/like/<int:pk>/', LikeView, name="like_name"),
    path('Showcase/User/flag/<int:pk>/', FlagView, name="flag_name")
]

projects_showcase/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path("", include('ItemApp.urls')),
    path("User/", include('UserApp.urls')),
    path('admin/', admin.site.urls),
    path('UserAdmin/', include('AdminApp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

database_manager/models.py
from django.forms import forms
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


# Create your models here.

#function to check the rate is below 5
def check_rate(num):
    if num > 5:
        return False
    return True

# class to create a new user
class MyUserManager(BaseUserManager):

    def create_user(self, email, username, name, password=None):
        #error if user is not correct
        if not email:
            raise ValueError("User must have an email")
        if not username:
            raise ValueError("User must have a username")
        if not name:
            raise ValueError("User must have a name")

        """
        Creates and saves a User with the given email, date of
        birth and password.
        """

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            name=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, name, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            name=username,
        )
        #give the admin all privileges
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_project_admin = True
        user.is_user_admin = True
        user.set_password(password)
        user.save(using=self._db)

        return user

# model for a user 
class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username = models.CharField(max_length=32, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined,', default=timezone.now)
    last_login = models.DateTimeField(verbose_name='last login', default=timezone.now)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_user_admin = models.BooleanField(default=False)
    is_project_admin = models.BooleanField(default=False)
    name = models.CharField(max_length=200, null=False, default="")
    status = models.IntegerField(default=0)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email', 'name']

    objects = MyUserManager()

    def __str__(self):  # __unicode__ on Python 2
        return self.name

    def get_username(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return self.is_admin

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

#model for a user's profile one to one relationship
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

# the status of a project
STATUS = (
    ("Ongoing", "Ongoing"),
    ("Planned", "Planned"),
    ("Completed", "Completed")
)
#the different rating choices
RATE_CHOICES = (
    (0, 0),
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
)

#class for a project that a single user can have
class Project(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    project_type = models.CharField(max_length=200)
    project_title = models.CharField(max_length=200, default="")
    keyword_list = models.CharField(max_length=1000)
    description = models.CharField(max_length=300)
    url = models.CharField(max_length=1000, blank=True)
    status = models.CharField(max_length=100, choices=STATUS, default="Ongoing")
    snapshot = models.ImageField(default=None, upload_to='details_pic', blank=True, null=True)
    publish_date = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name="like_name")
    flag = models.ManyToManyField(User, related_name="flag_name")

    def number_of_likes(self):
        return self.likes.count()

#automatically get current date
class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return timezone.now()

#model for a comment on a post by a user
class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, default="")
    comment = models.TextField(verbose_name="Write A Comment", max_length=500)
    create_date = models.DateTimeField(default=timezone.now)
    rate = models.IntegerField(validators=[check_rate], default=5, choices=RATE_CHOICES)

ItemApp/forms.py
from django import forms
from database_manager.models import Comment, Project, User

#from to create a new comment
class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'comment','rate']

#form to create a new Project
class NewProjectForm(forms.ModelForm):
    description = forms.TextInput(attrs={'rows': 1,
                                         'cols': 40,
                                         'style': 'height: 1em;'})
    class Meta:
        model = Project
        fields = [ 'project_title', 'project_type', 'keyword_list', 'description', 'url', 'status', 'snapshot']

ItemApp/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, ListView, DetailView, View, DeleteView, CreateView, UpdateView, DeleteView
from database_manager.models import Project, User, Comment
from .forms import NewCommentForm, NewProjectForm
from django.views.generic.edit import FormMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404


# Create your views here.

#get all the projects
class GetProjectsList(ListView):
    model = Project
    template_name = 'ItemApp/project_list.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    #filter the projects
    #seperate it in 3 , search, date, filter. 
    def get_queryset(self):
        qs = Project.objects.all()
        search = self.request.GET.get("search")
        my_date = self.request.GET.get("date")
        my_filter = self.request.GET.get("filter")

        #filter by date
        if my_date == "recent":
            qs = Project.objects.order_by('-publish_date')

        elif my_date == "oldest":
            qs = Project.objects.order_by('publish_date')

        #filter by liked flagged or  your own posts only
        if my_filter == "liked":
            qs = Project.objects.filter(likes=self.request.user)

        elif my_filter == "flagged":
            qs = Project.objects.filter(flag=self.request.user)

        elif my_filter == "my_posts":
            qs = Project.objects.filter(owner=self.request.user)

        #filter by search bar
        if search:
            #search if there is text
            if len(search) != 0:
                qs = qs.filter(project_title__contains=search) | qs.filter(keyword_list__contains=search) | qs.filter(
                    project_type__contains=search) | qs.filter(owner__name__contains=search)
        return qs

#get the details of the a single project
class GetProjectDetail(FormMixin, DetailView):
    model = Project
    template_name = 'ItemApp/project_detail.html'
    form_class = NewCommentForm

    #get the details  and comments of a specific project
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.get(pk=self.kwargs['pk'])
        context['comments'] = Comment.objects.filter(project=self.kwargs['pk'])
        #always give the chance for a new comment
        context['form'] = NewCommentForm()

        #make like like a boolean 
        likes_connected = get_object_or_404(Project, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['number_of_likes'] = likes_connected.number_of_likes()
        context['post_is_liked'] = liked

        # this is to calculatethe average of a post through its comments
        sumRate = 0
        counter = 0
        for com in context['comments']:
            sumRate = sumRate + com.rate
            counter = counter + 1

        if counter != 0:
            sumRate = sumRate / counter
        else:
            sumrate = -1
        context['number_of_rate'] = round(sumRate, 2)

        #make the flag like a boolean
        flag_connected = get_object_or_404(Project, id=self.kwargs['pk'])
        flagged = False
        if flag_connected.flag.filter(id=self.request.user.id).exists():
            flagged = True
        context['post_is_flagged'] = flagged

        return context

    # Handle POST GTTP requests
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    #check if the comment is valid
    def form_valid(self, form):
        comment = form.save(commit=False)
        #get the user who commented
        comment.user = self.request.user
        comment.project = Project.objects.get(pk=self.kwargs['pk'])
        comment.save()
        return super(GetProjectDetail, self).form_valid(form)

    #send it back to the same project
    def get_success_url(self):
        return reverse('project', kwargs={'pk': self.object.id})

#get all the projects made by the user only
class GetUserProjectsList(ListView):
    model = Project
    template_name = 'ItemApp/user_projects.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    # get only the users posts
    def get_queryset(self):
        qs = Project.objects.filter(owner=self.request.user)
        return qs

# allows a user to create a project
class CreateProject(CreateView):
    template_name = 'ItemApp/create_project.html'
    form_class = NewProjectForm

    #create the project
    def form_valid(self, form):
        Project = form.save(commit=False)
        #get the project creator
        Project.owner = self.request.user
        Project.save()
        return redirect('project', Project.pk)

# allows user to update a project
class UpdateProject(UpdateView):

    template_name = 'ItemApp/edit_project.html'
    form_class = NewProjectForm

    #update the current project
    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Project, pk=id_)

    #check if update is valid
    def form_valid(self, form):
        Project = form.save(commit=False)
        Project.save()
        return redirect('project', Project.pk)

    #make sure the user is looking at its own project
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not self.request.user.is_project_admin and obj.owner != self.request.user:
            raise Http404("You are not allowed to edit this Post")
        return super(UpdateProject, self).dispatch(request, *args, **kwargs)

# allows a user to delete a project
class DeleteProject(DeleteView):
    template_name = 'ItemApp/delete_project.html'
    model = Project
    #return to the all projects list
    success_url = reverse_lazy('showcase')

    #make sure the user is looking at its own project
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not self.request.user.is_project_admin and obj.owner != self.request.user:
            raise Http404("You are not allowed to Delete this Post")
        return super(DeleteProject, self).dispatch(request, *args, **kwargs)

#make the like button like a boolean
def LikeView(request, pk):
    post = get_object_or_404(Project, id=request.POST.get('like_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('project', args=[str(pk)]))

#make the like button like a boolean
def FlagView(request, pk):
    post = get_object_or_404(Project, id=request.POST.get('flag_id'))
    if post.flag.filter(id=request.user.id).exists():
        post.flag.remove(request.user)
    else:
        post.flag.add(request.user)
    return HttpResponseRedirect(reverse('project', args=[str(pk)]))

ItemApp/templates/ItemApp/create_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated %}
<style>

    #id_description{

    height: 100px;

    }
    input{
    width: 100%;
    }

  button{
  width: 100%;
    background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
    }

</style>

<h1 style=" width:50%;"> Create Project</h1>
<div class="content-section" style="float: left; width: 90%;
  border: 3px solid #73AD21;
  padding: 10px;">

    {% if messages %}
        {% for message in messages %}
            <div class="alert">
            {{ message }}
            </div>
         {% endfor %}
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset class="form-group" style="width:70%; display: block;">

            {{ form|crispy }}
        <div class="form-group">
            <button type="submit">Create Project</button>
        </div>
            </fieldset>
    </form>
    <div>

    </div>
</div>

{% else %}
<p>Please log in to create a new project</p>
{% endif %}


{% endblock content %}

ItemApp/templates/ItemApp/delete_project.html
{% extends 'base.html' %}
{% block content %}


<form action="." method="POST">
    {% csrf_token %}
    <h1>Do You want to delete this post {{ object.title }}</h1>
    <p><input class = "btn btn-primary" type="submit" value="Yes"/> <a class = "btn btn-primary" href="{% url 'showcase' %}">Cancel</a> </p>
</form>
{% endblock content %}

ItemApp/templates/ItemApp/edit_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated %}
<style>

    #id_description{
    
    height: 100px;

    }
    input{
    width: 100%;
    }

  button{
  width: 100%;
    background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
    }

</style>

<h1 style=" width:50%;"> Edit Project</h1>
<div class="content-section" style="float: left; width: 50%;
  border: 3px solid #73AD21;
  padding: 10px;">

    {% if messages %}
        {% for message in messages %}
            <div class="alert">
            {{ message }}
            </div>
         {% endfor %}
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset class="form-group" style="width:100%; display: block;">

            {{ form|crispy }}
        <div class="form-group">
            <button type="submit">Edit Project</button>
        </div>
            </fieldset>
    </form>
    <div>

    </div>
</div>

{% else %}
<p>Please log in to view your user account information</p>
{% endif %}


{% endblock content %}

ItemApp/templates/ItemApp/project_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<style>
.checked {
  color: orange;
}
#id_comment{
    height:40px;
}
</style>


    <div class="container-comment">
      <h2>Comment</h2>
      {% if user.is_authenticated %}
      
          <form method="POST">
              {% csrf_token %}
              {{form|crispy}}
              <div>
                  <button class = "btn btn-primary" type="submit">Comment</button>
              </div>
          </form>
     
      {%  else %}
          <p> <b> Sign In first! </b> </p>
      {% endif %}
    </div>
        

        <div class="card" style="margins: auto; width:90%; ">


            {% if project.snapshot %}
              <img class="card-img-top" style="width: 200px; margin: auto;" src="{{ project.snapshot.url }}">
            {% else %}
              <img class="card-img-top" src="https://www.elmhurst.edu/wp-content/uploads/2018/12/5-skills-project-management-degree-elmhurst-college-infographic-thumb.jpg" >
            {% endif %}
            <hr>
            <div class="card-body">
              <h5 class="card-title">{{ project.project_title }}</h5>
              <p class="card-text">Description: {{project.description}} </p>
              <p class="card-text">Type: {{ project.project_type }} </p>
              {% if project.url == '' %}
                 
             {% else %}
                <p class="card-text">Url: {{project.url}} </p>
                 
             {% endif %}
             <p class="card-text">Status: {{project.status}}</p>
             <p class="card-text">Overall Rating:
                 {% if number_of_rate == -1 %}
                  No Ratings Yet
                 {% else %}
                     {{ number_of_rate }}/5
                 {% endif %}
             </p>
              <p class="text-muted">{{ project.publish_date }} <br> By: {{ project.owner.name }}</p>
        
              {% if project.owner.username == user.username %}
                <a class="btn btn-primary " style="float:left; width:50%; " href="{% url 'update_project' project.id %}"> Edit</a>
                <a class="btn btn-primary " style="float:left; width:50%; " href="{% url 'delete_project' project.id %}"> Delete</a>
                
            </div>
              {% else %}
              <form style="float:right" action="{% url 'flag_name' project.id %}" method="POST">
                {% csrf_token %}
    
                {% if post_is_flagged %}
                <button type="submit" name="flag_id" value="{{project.id}}"> <img alt="Unflag!" style="width:45px" src="{% static 'flags/flagged.png' %}" /> </button>
                {% else %}
                <button type="submit" name="flag_id" value="{{project.id}}" > <img alt="Flag!" style="width:45px" src="{% static 'flags/flag.png' %}" /></button>
                {% endif %}
            </form>
            <p style="float:left" class="text">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</p>
        {% if user.is_authenticated %}
            <form  style="float:left" action="{% url 'like_name' project.id %}" method="POST">
                {% csrf_token %}
    
                {% if post_is_liked %}
                <button type="submit" name="like_id"  value="{{project.id}}">
                    <img alt="UNLIKE" style="width:25px" src="{% static 'likes/liked.png' %}" />
                </button>
                {% else %}
                <button type="submit" name="like_id" value="{{project.id}}"><img alt="LIKE!" style="width:25px" src="{% static 'likes/like.png' %}" /></button>
                {% endif %}
         {% endif %}
            </form>
              </div>
                 {% endif %}
                 
          <hr>
          <h3>Comments:</h3>
          {% if comments|length == 0 %}
          <p> <b> Write the Very first Comment On This Project! </b> </p>
          {% endif %}
          {% for com in comments %}
          <div id="comment-single">
              <h3 class="text">{{com.title}}</h3> 
              <p class="text">{{com.comment}}</p>
              <p  class="text">Rate:
                  {% if com.rate == 5 %}
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
      
                  {% endif%}
                  {% if com.rate == 4 %}
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star "></span>
      
                  {% endif%}
                  {% if com.rate == 3 %}
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
      
                  {% endif%}
                  {% if com.rate == 2 %}
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
      
                  {% endif%}
      
                  {% if com.rate == 1 %}
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
      
                  {% endif%}
                  {% if com.rate == 0 %}
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
                  <span class="fa fa-star "></span>
      
                  {% endif%}
      
              </p>
              <p class="small-text">From: {{com.user.name}}  on {{ com.create_date}}</p>
          </div>
          {% endfor %}
    </div>



<div style="margins: auto; width:90%;  id="comment-section">


    
 
</div>
{% endblock content %}

ItemApp/templates/ItemApp/project_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<style>
.card .card-block {max-height:300px;min-height:300px;overflow:auto;}
</style>
<div class="container-filter">
  <h2>Search </h2>
  <form method="GET">

    <input type="search" class="form-control" id="search" name="search" placeholder="title, type, keyword , author">
    <br>

    <input type="radio" id="recent" name="date" value="recent">
    <label for="recent">Most Recent</label>
    <input type="radio" id="oldest" name="date" value="oldest">
    <label for="oldest">Oldest</label>
    {% if user.is_authenticated%}
      <br>
      <input type="radio" id="liked" name="filter" value="liked">
      <label for="liked">Liked</label>
      <input type="radio" id="flagged" name="filter" value="flagged">
      <label for="flagged">Flagged</label>
      <input type="radio" id="my_posts" name="filter" value="my_posts">
      <label for="my_posts">My posts</label>
      <br>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="search">
  </form>
</div>

<div class="container-all-projects">


  {% for item in object_list %}

  <div class="card" style="width:85%; ">


    {% if item.project.snapshot %}
      <img class="card-img-top" src="{{ item.project.snapshot.url }}">
    {% else %}
      <img class="card-img-top" src="https://www.elmhurst.edu/wp-content/uploads/2018/12/5-skills-project-management-degree-elmhurst-college-infographic-thumb.jpg" >
    {% endif %}

    <div class="card-body">
      <h5 class="card-title">{{ item.project_title }}</h5>

      <p class="card-text">Type: {{ item.project_type }} </p>
      <p class="card-text">Keywords: {{ item.keyword_list }} </p>
      <p class="text-muted">{{ item.publish_date }} <br> By: {{ item.owner.name }}</p>

      {% if item.owner.username == user.username %}
        <a class="btn btn-primary stretched-link" style="float:left; width:33%; " href="{% url 'update_project' item.id %}"> Edit</a>
        <a class="btn btn-primary stretched-link" style="float:left; width:33%; " href="{% url 'delete_project' item.id %}"> Delete</a>
        <a href="{{ item.id }}" style="float:left; width:33%;" class="btn btn-primary stretched-link">Details</a>
      </div>
      {% else %}
      </div>
        <a href="{{ item.id }}" class="btn btn-primary stretched-link">Details</a>
      {% endif %}
  </div>
  {% endfor %}
</div>


{% if is_paginated  %}
  <section class="pagination" id="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
    {% else %}
      <span>&laquo;</span>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <span>{{ i }} (current)</span></span>
      {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% else %}
      <span>&raquo;</span>
    {% endif %}
  </section>
{% endif %}

{% endblock content %}

ItemApp/templates/ItemApp/user_projects.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-all-projects">

  {% if object_list|length == 0 %}
  <a href="{% url 'create_project' %}" class="btn btn-primary stretched-link">Create your first project</a>
  {% endif %}

  {% for item in object_list %}

  <div class="card" style="width:85%; ">


    {% if item.project.snapshot %}
      <img class="card-img-top" src="{{ item.project.snapshot.url }}">
    {% else %}
      <img class="card-img-top" src="https://www.elmhurst.edu/wp-content/uploads/2018/12/5-skills-project-management-degree-elmhurst-college-infographic-thumb.jpg" >
    {% endif %}

    <div class="card-body">
      <h5 class="card-title">{{ item.project_title }}</h5>

      <p class="card-text">Type: {{ item.project_type }} </p>
      <p class="card-text">Keywords: {{ item.keyword_list }} </p>
      <p class="text-muted">{{ item.publish_date }} <br> By: {{ item.owner.name }}</p>

      {% if item.owner.username == user.username %}
        <a class="btn btn-primary stretched-link" style="float:left; width:33%; " href="{% url 'update_project' item.id %}"> Edit</a>
        <a class="btn btn-primary stretched-link" style="float:left; width:33%; " href="{% url 'delete_project' item.id %}"> Delete</a>
        <a href="{{ item.id }}" style="float:left; width:33%;" class="btn btn-primary stretched-link">Details</a>
      </div>
      {% else %}
      </div>
        <a href="{{ item.id }}" class="btn btn-primary stretched-link">Details</a>
      {% endif %}
  </div>
  {% endfor %}
</div>


{% if is_paginated  %}
  <section id="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
    {% else %}
      <span>&laquo;</span>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <span>{{ i }} (current)</span></span>
      {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% else %}
      <span>&raquo;</span>
    {% endif %}
  </section>
{% endif %}

{% endblock content %}